# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-pg',
                'doc_host': 'https://matt-fff.github.io',
                'git_url': 'https://github.com/matt-fff/nbdev-pg',
                'lib_path': 'nbdev_pg'},
  'syms': {'nbdev_pg.core': {'nbdev_pg.core.foo': ('core.html#foo', 'nbdev_pg/core.py')}}}